package ec.espe.edu.HealthKeeper.Team3.view;

import javax.swing.JFrame; // Needed for JFrame.DISPOSE_ON_CLOSE

/**
 *
 * @author Maria Quiroz
 */
public class DietPlanAssignmentFrame extends javax.swing.JFrame {

    // Declare a private field to hold a reference to the parent MenuFrame
    private MenuFrame parentMenuFrame;

    /**
     * Creates new form DietPlanAssignmentFrame.
     * This constructor should be used when opening this frame from the MenuFrame.
     * @param parent The instance of the MenuFrame that opened this frame.
     */
    public DietPlanAssignmentFrame(MenuFrame parent) {
        this.parentMenuFrame = parent; // Store the reference to the parent menu frame
        initComponents();
        this.setLocationRelativeTo(null); // Center the frame on the screen
        setTitle("HealthKeeper - Diet Plan Assignment"); // Set a descriptive title for the frame
        // Set default close operation to DISPOSE_ON_CLOSE.
        // This ensures that only this window closes, and the application continues to run.
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * Default constructor for DietPlanAssignmentFrame.
     * This constructor might be used for independent testing, but in a multi-frame
     * application, it's generally better to use the parameterized constructor
     * to ensure the parent frame relationship is established.
     */
    public DietPlanAssignmentFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("HealthKeeper - Diet Plan Assignment (Standalone Test)");
        // No parentMenuFrame is set, so behavior will differ if "Back to Menu" is clicked.
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // Still dispose, not exit
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lTittle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lBreakfast = new javax.swing.JLabel();
        lLunch = new javax.swing.JLabel();
        lDinner = new javax.swing.JLabel();
        txtBreakfast = new javax.swing.JTextField();
        txtLunch = new javax.swing.JTextField();
        lSnacks = new javax.swing.JLabel();
        txtSnacks2 = new javax.swing.JTextField();
        txtDinner1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnDietPlan = new javax.swing.JButton();
        btnBackToMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lTittle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lTittle.setText("Diet plan");

        lBreakfast.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lBreakfast.setText("Breakfast:");

        lLunch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lLunch.setText("Lunch:");

        lDinner.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lDinner.setText("Dinner:");

        txtBreakfast.setBackground(new java.awt.Color(255, 255, 255));
        txtBreakfast.setForeground(new java.awt.Color(0, 0, 0));

        txtLunch.setBackground(new java.awt.Color(255, 255, 255));
        txtLunch.setForeground(new java.awt.Color(0, 0, 0));

        lSnacks.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lSnacks.setText("Snacks:");

        txtSnacks2.setBackground(new java.awt.Color(255, 255, 255));
        txtSnacks2.setForeground(new java.awt.Color(0, 0, 0));

        txtDinner1.setBackground(new java.awt.Color(255, 255, 255));
        txtDinner1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lBreakfast, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBreakfast, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lLunch, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lDinner, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lSnacks, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLunch)
                            .addComponent(txtSnacks2)
                            .addComponent(txtDinner1))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBreakfast, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lBreakfast, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLunch, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lLunch))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDinner))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSnacks2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lSnacks, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(lTittle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lTittle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnDietPlan.setBackground(new java.awt.Color(51, 204, 0));
        btnDietPlan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDietPlan.setForeground(new java.awt.Color(0, 0, 0));
        btnDietPlan.setText("Add diet plan");
        btnDietPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDietPlanActionPerformed(evt);
            }
        });

        btnBackToMenu.setBackground(new java.awt.Color(153, 102, 0));
        btnBackToMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBackToMenu.setForeground(new java.awt.Color(0, 0, 0));
        btnBackToMenu.setText("Back to menu");
        btnBackToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btnDietPlan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(btnBackToMenu)
                .addGap(63, 63, 63))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDietPlan)
                    .addComponent(btnBackToMenu))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(21, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 591, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(123, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDietPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDietPlanActionPerformed
        // This is where you'll add the logic to "add" or "save" the diet plan.
        // You'll likely gather the text from your JTextFields:
        String breakfastPlan = txtBreakfast.getText();
        String lunchPlan = txtLunch.getText();
        String dinnerPlan = txtDinner1.getText(); // Consider renaming txtDinner1 to txtDinner
        String snackPlan = txtSnacks2.getText(); // Consider if txtSnacks or txtSnacks2 is the primary one, or if both are used for different snacks.

        // For now, let's just print them to the console as a placeholder.
        System.out.println("Diet Plan Details:");
        System.out.println("Breakfast: " + breakfastPlan);
        System.out.println("Lunch: " + lunchPlan);
        System.out.println("Dinner: " + dinnerPlan);
        System.out.println("Snacks: " + snackPlan);


    }//GEN-LAST:event_btnDietPlanActionPerformed

    private void btnBackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMenuActionPerformed
        this.dispose(); // Close the current DietPlanAssignmentFrame

        // Check if the parent menu frame exists and make it visible
        if (parentMenuFrame != null) {
            parentMenuFrame.setVisible(true);
        } else {
            // This case should ideally not happen if the frame is always opened from MenuFrame.
            // It's a fallback for direct testing of this frame.
            System.err.println("Warning: parentMenuFrame was null. Opening a new MenuFrame.");
            new MenuFrame().setVisible(true); // Create a new MenuFrame instance
        }
    }//GEN-LAST:event_btnBackToMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DietPlanAssignmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DietPlanAssignmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DietPlanAssignmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DietPlanAssignmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // When running this frame directly for testing, pass null as there's no parent MenuFrame.
                // In your actual application, an instance of MenuFrame will be passed here.
                new DietPlanAssignmentFrame(null).setVisible(true); // Pass null for standalone testing
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToMenu;
    private javax.swing.JButton btnDietPlan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lBreakfast;
    private javax.swing.JLabel lDinner;
    private javax.swing.JLabel lLunch;
    private javax.swing.JLabel lSnacks;
    private javax.swing.JLabel lTittle;
    private javax.swing.JTextField txtBreakfast;
    private javax.swing.JTextField txtDinner1;
    private javax.swing.JTextField txtLunch;
    private javax.swing.JTextField txtSnacks2;
    // End of variables declaration//GEN-END:variables
}
