package ec.espe.edu.HealthKeeper.Team3.view;

import javax.swing.JFrame; // Needed for JFrame.DISPOSE_ON_CLOSE
import javax.swing.JOptionPane; // For user feedback messages

/**
 *
 * @author Maria Quiroz
 */
public class MedicationUpdateFrame extends javax.swing.JFrame {

    // Declare a private field to hold a reference to the parent MenuFrame
    private MenuFrame parentMenuFrame;

    /**
     * Creates new form MedicationUpdateFrame.
     * This constructor should be used when opening this frame from the MenuFrame.
     * @param parent The instance of the MenuFrame that opened this frame.
     */
    public MedicationUpdateFrame(MenuFrame parent) {
        this.parentMenuFrame = parent; // Store the reference to the parent menu frame
        initComponents();
        this.setLocationRelativeTo(null); // Center the frame on the screen
        setTitle("HealthKeeper - Medication Update"); // Set a descriptive title for the frame
        // Set default close operation to DISPOSE_ON_CLOSE.
        // This ensures that only this window closes, and the application continues to run.
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * Default constructor for MedicationUpdateFrame.
     * This constructor might be used for independent testing, but in a multi-frame
     * application, it's generally better to use the parameterized constructor
     * to ensure the parent frame relationship is established.
     */
    public MedicationUpdateFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("HealthKeeper - Medication Update (Standalone Test)");
        // No parentMenuFrame is set, so behavior will differ if "Back to Menu" is clicked.
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // Still dispose, not exit
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lTittleMedicationUpdate = new javax.swing.JLabel();
        lNewMedication = new javax.swing.JLabel();
        txtNewMedication = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnUpdateMedication = new javax.swing.JButton();
        btnBackToMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lTittleMedicationUpdate.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lTittleMedicationUpdate.setText("Medication update");

        lNewMedication.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lNewMedication.setText("New medication:");

        txtNewMedication.setBackground(new java.awt.Color(255, 255, 255));
        txtNewMedication.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(lTittleMedicationUpdate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(lNewMedication, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNewMedication, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lTittleMedicationUpdate)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lNewMedication, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNewMedication, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(277, 277, 277))
        );

        btnUpdateMedication.setBackground(new java.awt.Color(51, 204, 0));
        btnUpdateMedication.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdateMedication.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdateMedication.setText("Update medication");
        btnUpdateMedication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateMedicationActionPerformed(evt);
            }
        });

        btnBackToMenu.setBackground(new java.awt.Color(153, 102, 0));
        btnBackToMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBackToMenu.setForeground(new java.awt.Color(0, 0, 0));
        btnBackToMenu.setText("Back to menu");
        btnBackToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(btnUpdateMedication)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBackToMenu)
                .addGap(79, 79, 79))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateMedication)
                    .addComponent(btnBackToMenu))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateMedicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMedicationActionPerformed
        // This is where you'll add the logic to "update" the medication.
        String newMedication = txtNewMedication.getText();

        // Basic validation: Check if the text field is not empty
        if (newMedication.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the new medication details.",
                    "Input Error", JOptionPane.WARNING_MESSAGE);
            return; // Stop further execution if input is empty
        }

        // For now, let's just print it to the console as a placeholder.
        System.out.println("New Medication to Update: " + newMedication);

        // In a real application, you would typically:
        // 1. Create a Medication object or update an existing one with this data.
        // 2. Pass this data/object to a controller or manager class.
        // 3. The controller would then interact with your database (e.g., MongoDB for HealthKeeper)
        //    to perform the update operation.
        // 4. Provide user feedback (e.g., a JOptionPane.showMessageDialog saying "Medication updated successfully!").
        JOptionPane.showMessageDialog(this, "Medication update initiated (check console for details).",
                "Information", JOptionPane.INFORMATION_MESSAGE);

        // Clear the text field after successful "update"
        txtNewMedication.setText("");
    }//GEN-LAST:event_btnUpdateMedicationActionPerformed

    private void btnBackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMenuActionPerformed
        this.dispose(); // Close the current MedicationUpdateFrame

        // Check if the parent menu frame exists and make it visible
        if (parentMenuFrame != null) {
            parentMenuFrame.setVisible(true);
        } else {
            // This case should ideally not happen if the frame is always opened from MenuFrame.
            // It's a fallback for direct testing of this frame.
            System.err.println("Warning: parentMenuFrame was null. Opening a new MenuFrame.");
            new MenuFrame().setVisible(true); // Create a new MenuFrame instance
        }
    }//GEN-LAST:event_btnBackToMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicationUpdateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicationUpdateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicationUpdateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicationUpdateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // When running this frame directly for testing, pass null as there's no parent MenuFrame.
                // In your actual application, an instance of MenuFrame will be passed here.
                new MedicationUpdateFrame(null).setVisible(true); // Pass null for standalone testing
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToMenu;
    private javax.swing.JButton btnUpdateMedication;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lNewMedication;
    private javax.swing.JLabel lTittleMedicationUpdate;
    private javax.swing.JTextField txtNewMedication;
    // End of variables declaration//GEN-END:variables
}
